model:
    arch: linknet
data:
    dataset: ade20k
    train_split: training
    val_split: validation
    img_rows: 512
    img_cols: 512
    path: /data/fix_jer/ADE20K_2016_07_26/
training:
    train_iters: 300000
    batch_size: 1
    val_interval: 1000
    n_workers: 7
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume:
